name: Deploy to Server

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          set -e
          echo "Release ${{ github.event.release.tag_name }} detected"
          cd /home/sora81dev/discord-bot/nanase-bot
          git fetch --all --tags
          git checkout ${{ github.event.release.tag_name }}
          docker compose up -d --build